# Example input file.

# Parameters to control Monte Carlo loops
[MonteCarlo]
start_temperature = 0.0
end_temperature = 400.0
temperature_points_number = 200
relaxing_steps = 8000
counting_steps = 6000
flipping_number = 6000

# Information about the cell
[Lattice]
cell_number = [ 8, 8, 4 ] # A 8*8*4 supercell
tolerance = 0.01

# Magnetic elements
[[Elements]]
name = "Ni"
spin = 1.0
[[Elements.Neighbors]]
name = "Ir"
exchange_parameter = -7.5
distance = 4.02
[[Elements.Neighbors]]
name = "Ni"
exchange_parameter = 0.0
distance = 5.68

[[Elements]]
name = "Ir"
spin = 1.5
[[Elements.Neighbors]]
name = "Ni"
exchange_parameter = -7.5
distance = 4.02
[[Elements.Neighbors]]
name = "Ir"
exchange_parameter = 0.0
distance = 5.68

# Hamiltonian function
# Heisenberg type

# Initialization configuration
# Default initialization

# Parameters to control output
[Output]
magnifying_factor = 2.0