# Example input file.

# Parameters to control Monte Carlo loops
[MonteCarlo]
start_temperature = 0.0
end_temperature = 200.0
temperature_points_number = 200
relaxing_steps = 8000
counting_steps = 6000
flipping_number = 6000

# Information about the cell
[Lattice]
cell_number = [ 8, 8, 8 ] # A 8*8*8 supercell
tolerance = 0.01

# Magnetic elements
[[Elements]]
name = "Cr"
spin = 1.5
anisotropic_factor = [ 1.0, 1.0, 1.0 ]
[[Elements.Neighbors]]
name = "Cr"
exchange_parameter = -5.454
distance = 3.904
[[Elements.Neighbors]]
name = "Cr"
exchange_parameter = 0.079
distance = 10.28
[[Elements.Neighbors]]
name = "Cr"
exchange_parameter = 0.052
distance = 13.925

# Hamiltonian function
[Hamiltonian]
magnetic_field = [ 0.0, 0.5, 0.0 ]
anisotropy = [ 0.150, -0.150, -0.056 ]

# Initialization configuration
[Initialization]
angleA = [ 0.0, 0.0, 0.0 ] # Rotation angle between same kind of atoms of two nearby cell in a-axis reperesented by Euler angle. Use degree, not radians.
angleB = [ 0.0, 0.0, 0.0 ]
angleC = [ 180.0, 0.0, 0.0 ]
[[Initialization.Elements]] # Spin direction for atoms in first cell.
name = "Cr"
[[Initialization.Elements.Atoms]] # Spin direction for Cr1
spin_direction = [ 0.0, 1.0, 0.0] # Cartesian coordinate
[[Initialization.Elements.Atoms]] # Spin direction for Cr2
spin_direction = [ 0.0, -1.0, 0.0]

# Parameters to control output
[Output]
magnifying_factor = 2.0