name: release

on:
  push:
    tags:
      - "*"

jobs:
  export:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install xmake
        run: brew install xmake

      - name: Install xmake packages
        run: |
          xrepo update-repo
          xrepo install -y cmake
          xrepo install -y scnlib
          xrepo install -y fmt
          xrepo install -y ctre
          xrepo export -o ./packages

      - name: zip
        run: |
          cd ..
          zip -r MMC_offline.zip MMC

      - name: Upload artifacts
        uses: 'actions/upload-artifact@v2'
        with:
          name: MMC_offline.zip
          path: /home/runner/work/MMC/MMC_offline.zip

  release:
    needs: export
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: zip/

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: zip/MMC_offline.zip