name: release

on:
  push:
    tags:
      - "*"

jobs:
  export:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install xmake
        run: brew install xmake

      - name: Install xmake packages
        run: |
          xrepo update-repo
          xrepo install -y cmake
          xrepo install -y scnlib
          xrepo install -y fmt
          xrepo install -y ctre
          xrepo install -y spdlog
          xrepo install -y toml++
          xrepo export -o ./packages

      - name: zip
        run: zip -r MMC_offline.zip ./

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: MMC_offline.zip
          asset_name: MMC_offline.zip
          tag: ${{ github.ref }}
          overwrite: true