name: release

on:
  push:
    tags:
      - "*"

jobs:
  export:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Prune
        run: |
          rm -rf .git
          rm -rf .github
          rm -rf submodules/ctre/tests
          rm -rf submodules/fmt/test
          rm -rf submodules/scnlib/test
          rm -rf submodules/toml++/external
          rm -rf submodules/toml++/tests

      - name: zip
        run: |
          zip -r MMC.zip ./

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: MMC.zip
          asset_name: MMC.zip
          tag: ${{ github.ref }}
          overwrite: true