name: release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install xmake
        run: brew install xmake

      - name: Install packages
        run: |
          brew install open-mpi
          brew install boost
          brew install boost-mpi
        
      - name: Build the target
        run: |
          xmake f -y -m debug
          xmake -y -rv

      - name: Upload artifacts
        uses: 'actions/upload-artifact@v2'
        with:
          name: MMC_${{ runner.os }}
          path: MMC

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: build/

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}